services:
  bot:
    build: .
    container_name: vacancies_bot
    restart: unless-stopped
    depends_on:
      - redis
    ports:
      - 5678:5678
    env_file:
      - .env
  
  redis:
    image: redis:8-alpine
    container_name: vacancies_redis
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    command: redis-server --requirepass pass --appendonly yes
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  redis_data:
